# Generated by Django 4.0.4 on 2022-05-19 11:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecentSearches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(blank=True, max_length=150)),
                ('search_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
