branch-defaults:
  main:
    environment: django-env
    group_suffix: null
global:
  application_name: django-app
  branch: null
  default_ec2_keyname: travel-smart-key
  default_platform: Python 3.8
  default_region: eu-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
